### ISSUE TITLE
Big picture to-do's

### ISSUE THREAD

**Issue by ethan-pierce** [ethan-pierce/greenland-ird#1]
- [x] Prepare input datasets
    - [x] Delineate basin outlines
    - [x] Pre-process ice thickness
    - [x] Pre-process surface velocity
    - [x] Format observation.nc file
- [x] Generate computational mesh
    - [x] Build Landlab TriangleMeshGrid
    - [x] Interpolate gridded data  
- [x] Develop hydrology model
    - [x] Write algorithm
    - [x] Implement ODE solver
    - [x] Conserve mass by optimization
    - [x] Translate to JAX for performance
- [ ] Run IGM inverse method
- [ ] Compile field data
- [ ] Run sediment transport model
- [ ] Produce draft figures
